## @file
# Subclass of NewPackage, which is generated by wxFormBuilder.
#
# Copyright (c) 2012, Intel Corporation. All rights reserved.<BR>
#
# This program and the accompanying materials are licensed and made available
# under the terms and conditions of the BSD License which accompanies this
# distribution. The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
##

"""Subclass of NewPackage, which is generated by wxFormBuilder."""

##
# Import Modules
#
import Config
import wx
import os
import sys
import uuid
import string
import TemplateString
import UefiDriverWizard
import UefiDriverWizardNewPackage
import UefiDriverWizardNewUefiDriver
import UefiDriverWizardNewProtocol
import UefiDriverWizardNewGuid
import UefiDriverWizardNewLibraryClass
import UefiDriverWizardUefiDriverWizard
import UefiDriverWizardUefiDriverModelOptionalFeatures
import UefiDriverWizardUefiDriverModelConsumedProtocols
import UefiDriverWizardUefiDriverModelProducedProtocols

# Implementing NewPackage
class UefiDriverWizardNewPackage( UefiDriverWizard.NewPackage ):
  def __init__( self, parent ):
    UefiDriverWizard.NewPackage.__init__( self, parent )
    if (Config.PackagePath):
      self.PackagePath.SetPath(Config.PackagePath + os.path.sep)
    else:
      self.PackagePath.SetPath(Config.WorkspacePath + os.path.sep)
    if Config.PackageName == '':
      Config.PackageName = os.path.split(Config.PackagePath)[-1]
    self.PackageName.SetValue(Config.PackageName)
    if Config.PackageGuidValue == '':
      Config.PackageGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.PackageGuidValue.SetValue(Config.PackageGuidValue)
    self.PackageVersion.SetValue(Config.PackageVersion)
    if Config.PlatformGuidValue == '':
      Config.PlatformGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.PlatformGuidValue.SetValue(Config.PlatformGuidValue)

  # Handlers for NewPackage events.
  def PackagePathOnDirChanged( self, event ):
    if Config.PackageName == '' or Config.PackageName == os.path.split(Config.PackagePath)[1]:
      Config.PackagePath = self.PackagePath.GetPath()
      self.PackageName.SetValue(os.path.split(Config.PackagePath)[1])
    else:
      Config.PackagePath = self.PackagePath.GetPath()

  def PackageNameOnText( self, event ):
    Config.PackageName = Config.App.TextFieldNameValid (self.PackageName, event)

  def PackageGuidValueOnText( self, event ):
    Config.PackageGuidValue = event.GetString()

  def GenerateGuidOnButtonClick( self, event ):
    Config.PackageGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.PackageGuidValue.SetValue(Config.PackageGuidValue)

  def PackageVersionOnText( self, event ):
    Config.PackageVersion = Config.App.TextFieldVersionValid (self.PackageVersion, event)

  def PlatformGuidValueOnText( self, event ):
    Config.PlatformGuidValue = event.GetString()

  def GeneratePlatformGuidOnButtonClick( self, event ):
    Config.PlatformGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.PlatformGuidValue.SetValue(Config.PlatformGuidValue)

  def FinishOnButtonClick( self, event ):
    if Config.PackageName == '':
      Config.PackageName = os.path.split(Config.PackagePath)[-1]
    Result, Message = Config.App.CreatePackage()
    if not Result:
      dlg = wx.MessageDialog(
            self,
            Message,
            'ERROR',
            wx.OK | wx.ICON_ERROR
            )
      dlg.ShowModal()
      dlg.Destroy()
      return
    dlg = wx.MessageDialog(
          self,
          Message,
          'New Package',
          wx.OK | wx.ICON_INFORMATION
          )
    dlg.ShowModal()
    dlg.Destroy()
    Config.PackageName       = ''
    Config.PackageGuidValue  = ''
    Config.PackageVersion    = ''
    Config.PlatformGuidValue = ''
    self.Destroy()

  def CancelOnButtonClick( self, event ):
    Config.PackageName       = ''
    Config.PackageGuidValue  = ''
    Config.PackageVersion    = ''
    Config.PlatformGuidValue = ''
    self.Destroy()
