## @file
# Subclass of NewProtocol, which is generated by wxFormBuilder.
#
# Copyright (c) 2012, Intel Corporation. All rights reserved.<BR>
#
# This program and the accompanying materials are licensed and made available
# under the terms and conditions of the BSD License which accompanies this
# distribution. The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#
##

"""Subclass of NewProtocol, which is generated by wxFormBuilder."""

##
# Import Modules
#
import Config
import wx
import os
import sys
import uuid
import string
import TemplateString
import UefiDriverWizard
import UefiDriverWizardNewPackage
import UefiDriverWizardNewUefiDriver
import UefiDriverWizardNewProtocol
import UefiDriverWizardNewGuid
import UefiDriverWizardNewLibraryClass
import UefiDriverWizardUefiDriverWizard
import UefiDriverWizardUefiDriverModelOptionalFeatures
import UefiDriverWizardUefiDriverModelConsumedProtocols
import UefiDriverWizardUefiDriverModelProducedProtocols

# Implementing NewProtocol
class UefiDriverWizardNewProtocol( UefiDriverWizard.NewProtocol ):
  def __init__( self, parent ):
    UefiDriverWizard.NewProtocol.__init__( self, parent )
    if Config.PackageFile <> '':
      self.PackageFile.SetPath(Config.PackageFile)
    else:
      if Config.PackagePath <> '':
        self.PackageFile.SetPath(Config.PackagePath + os.path.sep)
      else:
        self.PackageFile.SetPath(Config.WorkspacePath + os.path.sep)
    if Config.ProtocolGuidValue == '':
      Config.ProtocolGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.ProtocolGuidValue.SetValue(Config.ProtocolGuidValue)
    self.ProtocolIncludeName.SetValue(Config.ProtocolIncludeName)

  # Handlers for NewProtocol events.
  def PackageFileOnFileChanged( self, event ):
    Config.PackageFile = self.PackageFile.GetPath()

  def ProtocolGuidValueOnText( self, event ):
    Config.ProtocolGuidValue = event.GetString()

  def GenerateGuidOnButtonClick( self, event ):
    Config.ProtocolGuidValue = uuid.uuid1().get_urn().split(':')[2]
    self.ProtocolGuidValue.SetValue(Config.ProtocolGuidValue)

  def ProtocolIncludeNameOnText( self, event ):
    Config.ProtocolIncludeName = Config.App.TextFieldNameValid (self.ProtocolIncludeName, event)

  def FinishOnButtonClick( self, event ):
    Result, Message = Config.App.CreateProtocol()
    if not Result:
      dlg = wx.MessageDialog(
            self,
            Message,
            'ERROR',
            wx.OK | wx.ICON_ERROR
            )
      dlg.ShowModal()
      dlg.Destroy()
      return
    dlg = wx.MessageDialog(
          self,
          Message,
          'New Protocol',
          wx.OK | wx.ICON_INFORMATION
          )
    dlg.ShowModal()
    dlg.Destroy()
    Config.ProtocolGuidValue = ''
    Config.ProtocolIncludeName = ''
    self.Destroy()

  def CancelOnButtonClick( self, event ):
    Config.ProtocolGuidValue = ''
    Config.ProtocolIncludeName = ''
    self.Destroy()
